classDiagram
    %% ===== Абстракції =====
    class Participant {
    <<abstract>>
    -id: int
    -name: String
    +getRole(): String
}


class IProjectChangeHandler {
    <<interface>>
    +handleChange(c: ProjectChange)
}


    %% ===== Конкретні учасники =====
class Foreman {
    -experienceYears: int
    +Foreman(id, name, experienceYears)
    +initiateChange(desc): ProjectChange
    +closeStage(): void
}


class Engineer {
    -licenseNumber: String
    +Engineer(id, name, licenseNumber)
    +approveChange(c: ProjectChange): boolean
    +updateSchedule(): void
}


class Supplier {
    -companyName: String
    +Supplier(id, name, companyName)
    +deliverMaterials(): void
}


%% ===== Бізнес-обʼєкти =====
class ConstructionProject {
    -title: String
    -changes: List<ProjectChange>
    +ConstructionProject(title)
    +addChange(c: ProjectChange)
    +final getStatus(): String
}


class ProjectChange {
    -description: String
    -impact: String
    +ProjectChange(desc, impact)
}


%% ===== Звʼязки =====
    Participant <|-- Foreman
    Participant <|-- Engineer
    Participant <|-- Supplier


    IProjectChangeHandler <|.. Foreman
    IProjectChangeHandler <|.. Engineer


    Foreman --> ProjectChange : creates
    Engineer --> ProjectChange : reviews



    ConstructionProject o-- ProjectChange : aggregation
    Supplier ..> ConstructionProject : dependency